# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME_Constraints.xdc

# IP: ip/Text/Text.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Text || ORIG_REF_NAME==Text} -quiet] -quiet
