# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME_Constraints.xdc

# IP: ip/Graphics/Graphics.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Graphics || ORIG_REF_NAME==Graphics} -quiet] -quiet
