# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/EXPLOSION_AUDIO/EXPLOSION_AUDIO.xci
# IP: The module: 'EXPLOSION_AUDIO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/EXPLOSION_AUDIO/EXPLOSION_AUDIO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EXPLOSION_AUDIO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/EXPLOSION_AUDIO/EXPLOSION_AUDIO.xci
# IP: The module: 'EXPLOSION_AUDIO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/EXPLOSION_AUDIO/EXPLOSION_AUDIO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EXPLOSION_AUDIO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
