# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/WINLOSE/WINLOSE.xci
# IP: The module: 'WINLOSE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/WINLOSE/WINLOSE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'WINLOSE'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/WINLOSE/WINLOSE.xci
# IP: The module: 'WINLOSE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AdoneyGalvan/Vivado Projects/GAME/GAME.srcs/sources_1/ip/WINLOSE/WINLOSE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'WINLOSE'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
